bincontest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("resulst.urls"))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resulst/urls.py
from django.urls import path

from . import views

app_name="resulst"
urlpatterns = [
    path("",views.index.as_view(),name="index"),
    path('pullingresult',views.pullingresult.as_view(),name="pullingresult"),

    path("newresults",views.newresults.as_view(),name="newresults")
]

resulst/models.py
from django.db import models

# Create your models here.

class Agentname(models.Model):
    name_id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    email = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=13)
    pollingunit_uniqueid = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'agentname'


class AnnouncedLgaResults(models.Model):
    result_id = models.AutoField(primary_key=True)
    lga_name = models.CharField(max_length=50)
    party_abbreviation = models.CharField(max_length=4)
    party_score = models.IntegerField()
    entered_by_user = models.CharField(max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'announced_lga_results'

class States(models.Model):
    state_id = models.IntegerField(primary_key=True)
    state_name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'states'
        

class Lga(models.Model):
    uniqueid = models.AutoField(primary_key=True)
    lga_id = models.IntegerField()
    lga_name = models.CharField(max_length=50)
    # state_id = models.IntegerField()
    state_id = models.ForeignKey(States,on_delete=models.CASCADE,db_column='state_id')
    lga_description = models.TextField(blank=True, null=True)
    entered_by_user = models.CharField(max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'lga'


class PollingUnit(models.Model):
    uniqueid = models.AutoField(primary_key=True)
    polling_unit_id = models.IntegerField()
    ward_id = models.IntegerField()
    #lga_id = models.IntegerField()
    lga_id = models.ForeignKey(Lga,on_delete=models.CASCADE, db_column='lga_id')
    uniquewardid = models.IntegerField(blank=True, null=True)
    polling_unit_number = models.CharField(max_length=50, blank=True, null=True)
    polling_unit_name = models.CharField(max_length=50, blank=True, null=True)
    polling_unit_description = models.TextField(blank=True, null=True)
    lat = models.CharField(max_length=255, blank=True, null=True)
    long = models.CharField(max_length=255, blank=True, null=True)
    entered_by_user = models.CharField(max_length=50, blank=True, null=True)
    date_entered = models.DateTimeField(blank=True, null=True)
    user_ip_address = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'polling_unit'



class AnnouncedPuResults(models.Model):
    result_id = models.AutoField(primary_key=True)
    polling_unit_uniqueid = models.ForeignKey(PollingUnit,on_delete=models.CASCADE,db_column="polling_unit_uniqueid")
    party_abbreviation = models.CharField(max_length=4)
    party_score = models.IntegerField()
    entered_by_user = models.CharField(max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'announced_pu_results'


class AnnouncedStateResults(models.Model):
    result_id = models.AutoField(primary_key=True)
    state_name = models.CharField(max_length=50)
    party_abbreviation = models.CharField(max_length=4)
    party_score = models.IntegerField()
    entered_by_user = models.CharField(max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'announced_state_results'


class AnnouncedWardResults(models.Model):
    result_id = models.AutoField(primary_key=True)
    ward_name = models.CharField(max_length=50)
    party_abbreviation = models.CharField(max_length=4)
    party_score = models.IntegerField()
    entered_by_user = models.CharField(max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'announced_ward_results'



        



class Party(models.Model):
    partyid = models.CharField(max_length=11)
    partyname = models.CharField(max_length=11)

    class Meta:
        managed = False
        db_table = 'party'








class Ward(models.Model):
    uniqueid = models.AutoField(primary_key=True)
    ward_id = models.IntegerField()
    ward_name = models.CharField(max_length=50)
    lga_id = models.IntegerField()
    ward_description = models.TextField(blank=True, null=True)
    entered_by_user = models.CharField(max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'ward'

resulst/views.py
from django.shortcuts import render

from django.views import View
# Create your views here.
from .models import AnnouncedLgaResults,PollingUnit,AnnouncedPuResults,Party,Ward,Lga

class index(View):
    def get(self,request):
        title="INEC"
        results=AnnouncedLgaResults.objects.all()
        pullinguint=PollingUnit.objects.select_related('lga_id')
        # if pullinguint.exists():
        #     for p in pullinguint:
        #         print("lag",p.lga_id.state_id.state_name)
        #     else:
        #         print("none")
        # print(pullinguint.query)
        context={"title":title,"results":results,"pullinguint":pullinguint}
        return render(request,"pages/index.html",context)



class pullingresult(View):
    def get(self,request):
        
        announcedpresults=AnnouncedPuResults.objects.all()
        context={"announcedpresults":announcedpresults}
        return render(request,'pages/pullingresults.html',context)
    


class newresults(View):
    def get(self,request):
        party=Party.objects.all()
        pullingunit=PollingUnit.objects.all()
        ward=Ward.objects.all()
        lga=Lga.objects.all()
        context={"party":party,'pullingunit':pullingunit,'ward':ward,"lga":lga}

        return render(request,'pages/newresults.html',context)

    def post(self,request):
        pass

resulst/templates/layouts/banner.html
{% load static %}
<div class="banner">
    <img src="{% static 'img/banner1.png' %}" alt="">
</div>

<style>
    .banner{
        margin-bottom: 30px;
    }
    .banner img{
        height: 450px !important;
        width: 100% !important;
    }
</style>

resulst/templates/layouts/based.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0560d0caf7.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include 'layouts/nav.html' %}
    {% block content %}{% endblock  %}
</body>
</html>

resulst/templates/layouts/nav.html
<nav>
   
        <li>Chika Nwazuo</li>
   
    <ul class="ulnave">
        <li><a href="/">Home</a></li>
        <li><a href="{%url 'resulst:pullingresult'%}">Total Results</a></li>
        <li><a href="{% url 'resulst:newresults' %}">Add new results</a></li>
    </ul>
   
   <button class="mobile" onclick="openmobile()"><i class="fa-solid fa-bars"></i></button>
</nav>
<script>
    function openmobile(){
        const openmobilebar=document.querySelector(".ulnave")
        openmobilebar.classList.toggle("showmobile")
       
    }
</script>
<style>
    body,html{
        overflow-x: hidden !important;
    }
    .mobile{
        display: none;
    }
    @media (max-width:900px){
        .mobile i{
            width: 34px;
            
        }
        .mobile{
         display: block !important;
         background-color: transparent;
         width: 30px;
         height: 30px;
         cursor: pointer;
         border: none;
        }
        .showmobile{
            display: flex !important;
            background-color: white !important;
            flex-direction: column;
            align-items: center;
        }
             nav{
                 align-items: unset;
                 position: relative;
             }
             .ulnave{
                flex-direction: column;
                position: absolute;
                top: 30px;
               
                background-color: black !important;
                z-index: 99;
                display: none;
                width: 100vw !important;
             }
             
            .ulnave li a{
                color: white;
            }
     
             
         } 
</style>

resulst/templates/pages/index.html
{% extends 'layouts/based.html' %}

{% block title %}{{title}}{% endblock  %}


{% block content %}

<div class="container">
  {% include 'layouts/banner.html' %}
  <h1>Welcome to INEC vitural plartform</h1>
  <h2>Pulling Units</h2>

<table class="table">
    <thead>
      <tr>
        <th scope="col">Pulling unit name</th>
        <th scope="col">Pulling unit number</th>
        <th scope="col">description</th>
        {% comment %} <th scope="col">lat</th> {% endcomment %}
        <th scope="col">LGA</th>
        <th scope="col">State</th>
      </tr>
    </thead>
    <tbody>
        {% for pulling in pullinguint %}
        <tr>
            <th>{{pulling.polling_unit_name}}</th>
            <td>{{pulling.polling_unit_number}}</td>
            <td>{{pulling.polling_unit_description}}</td>
            {% comment %} <td>{{pulling.lat}}</td> {% endcomment %}
            <td>{{ pulling.lga_id.lga_name }}</td>
            <td>{{ pulling.lga_id.state_id.state_name }} State</td>
          </tr>
          {% endfor %}
     
    </tbody>
  </table>
</div>
    

{% endblock  %}

resulst/templates/pages/newresults.html
{% extends 'layouts/based.html' %}

{% block title %}{{title}}{% endblock  %}


{% block content %}
<div class="container">
  <h1>Welcome to INEC vitural plartform</h1>
  <h2>Pulling Units</h2>

<form action="#">
 <select name="" id="">
  <option value="">Selete Pulling unit</option>
  {% for pullingunit in pullingunit %}
  <option value="{{ polling_unit_id }}">{{ pullingunit.polling_unit_name }}</option>    
  {% endfor %}
    
 </select>
 <select>
  <option value="">Party</option>
  
  {% for p in party %}
    <option value="{{ p.partyid }}">{{ p.partyname }} </option>
  {% endfor %}
    
 </select>
 <select>
  <option value="">LGA</option>
  
  {% for lga in lga %}
    <option value="{{ lga.lga_id }}">{{ lga.lga_name }} </option>
  {% endfor %}
    
 </select>
 <select>
  <option value="">Ward</option>
  
  {% for w in ward %}
  <option value="{{ w.ward_id }}">{{ w.ward_name }}</option>
    
  {% endfor %}
    
 </select>
 <input type="text" name="party_score">

 <input type="submit" value="Submit">
 <div>
  <p>This form wasn't completed due to time please</p>
 </div>
</form>
</div>
    

{% endblock  %}

resulst/templates/pages/pullingresults.html
{% extends 'layouts/based.html' %}

{% block title %}{{title}}{% endblock  %}


{% block content %}
<div class="container">
  <h1>Welcome to INEC vitural plartform</h1>


<table class="table">
    <thead>
      <tr>
        <th scope="col">Pulling unit name</th>
        <th scope="col">Party</th>
        <th scope="col">Scors</th>
        {% comment %} <th scope="col">lat</th> {% endcomment %}
        <th scope="col">LGA</th>
        {% comment %} <th scope="col">State</th> {% endcomment %}
      </tr>
    </thead>
    <tbody>
        {% for r in announcedpresults %}
        <tr>
          <th>{{r.polling_unit_uniqueid.polling_unit_name}}</th>
          <th>{{r.party_abbreviation}}</th>
            <th>{{r.party_score}}</th>
            <th>{{r.polling_unit_uniqueid.lga_id.lga_name}}</th>
           
            
          </tr>
          {% endfor %}
     
    </tbody>
  </table>
</div>

    

{% endblock  %}